config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
                       registrations: 'users/registrations',
                       sessions: 'users/sessions'
                     }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'homes/about'

  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'users/leave'
      patch 'users/active_leave'
    end
  end
  resources :exhibitions, only: [:index, :show] do
    resource :congestions, only: [:create]
    resource :clips, only: [:create, :destroy]
  end
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  has_many :clips, dependent: :destroy
  has_many :congestions, dependent: :destroy
  has_many :users, through: :clips

  mount_uploader :image, ImageUploader

  validates :name, presence: true, length: { maximum: 50 }
  validates :place, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :image, presence: true
  validates :description, presence: true, length: { maximum: 2000 }
  validates :summary, presence: true, length: { maximum: 2000 }
  validates :status, presence: true

  def congested_by?(user)
    congestions.where(user_id: user.id).exists?
  end

  def clipped_by?(user)
    clips.where(user_id: user.id).exists?
  end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :authenticate_user!
  before_action :congestion_delete, only: [:index, :show]

  def index
  	@exhibitions = Exhibition.all
  end

  def show
  	@exhibition = Exhibition.find(params[:id])
  end

  private
  def congestion_delete
    Congestion.where("created_at<?",Time.current.ago(1.hours)).delete_all
  end

  def exhibition_params
    params.require(:exhibition).permit(:name, :place, :start, :end, :image, :description, :summary, :status)
  end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/index.html.erb
<!-- indexヘディング -->
<div class="row exhibitionIndexHeading"></div>
<h2 class="col-lg-12 exhibitionIndexHeading_heading">開催中展覧会一覧</h2>
  <p class="col-lg-12 exhibitionIndexHeading_pragraph">
	※混雑度は <%= Time.current.ago(1.hours).strftime("%H時%M分") %> 〜 <%= Time.current.strftime("%H時%M分") %> の実況数
  </p>

<!-- indexメイン -->
<div class="d-flex flex-wrap justify-content-around exhibitionIndexMain">
<% @exhibitions.each do |exhibition| %>
  <% if "Now" == exhibition.status %>
  <!-- 開催中のみ表示 -->
      <ul class="flex-colmun exhibitionIndexMain-ul">
		<li class="exhibitionIndexMain-ul_li-name"><%= link_to exhibition.name, exhibition_path(exhibition), class: "exhibitionIndexMain-ul_li-nameLink" %>
		  <!-- クリップ未・済の分岐 -->
		  <% if exhibition.clipped_by?(current_user) %>
		  	<!-- クリップ済み -->
   		    <%= link_to exhibition_clips_path(exhibition), class: "exhibitionIndexMain-ul_li-clippedLink", method: :delete do %>
      	      <i class="fas fa-paperclip"></i>
            <% end %>
          <% else %>
          	<!-- 未クリップ -->
            <%= link_to exhibition_clips_path(exhibition), class: "exhibitionIndexMain-ul_li-clipLink", method: :post do %>
      	      <i class="fas fa-paperclip"></i>
            <% end %>
          <% end %>
        </li>
		<li class="exhibitionIndexMain-ul_li-place">会場：<%= exhibition.place %></li>
		<li class="exhibitionIndexMain-ul_li-period">
			会期：<%= exhibition.start.strftime("%Y年%m月%d日") %> 〜 <%= exhibition.end.strftime("%Y年%m月%d日") %>
		</li>
		<li class="exhibitionIndexMain-ul_li-image"><%= link_to (exhibition) do %>
		  <%= image_tag exhibition.image.url(:thumb), class: "exhibitionIndexMain-ul_li-imageTag" %><br>
		  <% end %>
		</li>
		<!-- 混雑度投稿の未・済の分岐 -->
		<% if exhibition.congested_by?(current_user) %>
		  <!-- 投稿済み -->
		  <li class="d-flex flex-row justify-content-around exhibitionIndexMain-ul_li-buttons">
			<button class="exhibitionIndexMain-ul_li-button btn btn-secondary" disabled="disabled">混んでる<br>
			  <%= exhibition.congestions.where(condition: "high").count %>人</button>
			<button class="exhibitionIndexMain-ul_li-button btn btn-secondary" disabled="disabled">やや混雑<br>
			  <%= exhibition.congestions.where(condition: "middle").count %>人</button>
			<button class="exhibitionIndexMain-ul_li-button btn btn-secondary" disabled="disabled">空いてる<br>
			  <%= exhibition.congestions.where(condition: "low").count %>人</button>
		  </li>
		<% else %>
		  <!-- 未投稿 -->
		  <li class="d-flex flex-row justify-content-around exhibitionIndexMain-ul_li-yetButtons">
		  	<%= button_to exhibition_congestions_path(exhibition), class: "exhibitionIndexMain-ul_li-yetButton btn btn-secondary", params: { condition: "high" } do %>混んでる<br>
		  	  <%= exhibition.congestions.where(condition: "high").count %>人
		    <% end %>
		    <%= button_to exhibition_congestions_path(exhibition), class: "exhibitionIndexMain-ul_li-yetButton btn btn-secondary", params: { condition: "middle" } do %>やや混雑<br>
		  	  <%= exhibition.congestions.where(condition: "middle").count %>人
		    <% end %>
		    <%= button_to exhibition_congestions_path(exhibition), class: "exhibitionIndexMain-ul_li-yetButton btn btn-secondary", params: { condition: "low" } do %>空いてる<br>
		  	  <%= exhibition.congestions.where(condition: "low").count %>人
		    <% end %>
		  </li>
		<% end %>
	  </ul>
  <% end %>
<% end %>
</div>

app/views/exhibitions/show.html.erb
<!-- showメイン -->
<div class="exhibitionShowMain1">
  <h1 class="exhibitionShowMain1_name"><%= @exhibition.name %>
    <!-- クリップ未・済の分岐 -->
    <% if @exhibition.clipped_by?(current_user) %>
      <!-- クリップ済み -->
	  <%= link_to exhibition_clips_path(@exhibition), class: "exhibitionShowMain1_clippedLink", method: :delete do %>
	    <i class="fas fa-paperclip"></i>
      <% end %>
    <% else %>
  	  <!-- 未クリップ -->
      <%= link_to exhibition_clips_path(@exhibition), class: "exhibitionShowMain1_clipLink", method: :post do %>
	    <i class="fas fa-paperclip"></i>
      <% end %>
    <% end %>
  </h1>
  <p class="exhibitionShowMain1_place">会場：<%= @exhibition.place %></p>
  <p class="exhibitionShowMain1_period">
	会期：<%= @exhibition.start.strftime("%Y年%m月%d日") %> 〜 <%= @exhibition.end.strftime("%Y年%m月%d日") %>
  </p>
  <!-- 混雑度投稿の未・済の分岐 -->
  <div class="d-flex flex-row flex-wrap justify-content-around exhibitionShowMain1-button">
    <% if @exhibition.congested_by?(current_user) %>
      <!-- 投稿済み -->
      <button class="exhibitionShowMain1-button_button btn btn-secondary" disabled="disabled">混んでる<br>
  	    <%= @exhibition.congestions.where(condition: "high").count %>人</button>
      <button class="exhibitionShowMain1-button_button btn btn-secondary" disabled="disabled">やや混雑<br>
  	    <%= @exhibition.congestions.where(condition: "middle").count %>人</button>
      <button class="exhibitionShowMain1-button_button btn btn-secondary" disabled="disabled">空いてる<br>
  	    <%= @exhibition.congestions.where(condition: "low").count %>人</button>
    <% else %>
      <!-- 未投稿 -->
      <%= button_to exhibition_congestions_path(@exhibition), class: "exhibitionShowMain1-button_yetButton btn btn-secondary", params: { condition: "high" } do %>混んでる<br>
  	    <%= @exhibition.congestions.where(condition: "high").count %>人</button>
      <% end %>
      <%= button_to exhibition_congestions_path(@exhibition), class: "exhibitionShowMain1-button_yetButton btn btn-secondary", params: { condition: "middle" } do %>やや混雑<br>
  	    <%= @exhibition.congestions.where(condition: "middle").count %>人</button>
      <% end %>
      <%= button_to exhibition_congestions_path(@exhibition), class: "exhibitionShowMain1-button_yetButton btn btn-secondary", params: { condition: "low" } do %>空いてる<br>
  	    <%= @exhibition.congestions.where(condition: "low").count %>人</button>
      <% end %>
    <% end %>
  </div>
  <p class="col-lg-12 exhibitionShowMain1_heed">
	  ※混雑度は <%= Time.current.ago(1.hours).strftime("%H時%M分") %> 〜 <%= Time.current.strftime("%H時%M分") %> の実況数
  </p>
  <div class="exhibitionShowMain1_image"><%= link_to (@exhibition) do %>
    <%= image_tag @exhibition.image.to_s, class: "exhibitionShowMain1_imageTag" %>
    <% end %>
  </div>
</div>
<div class="exhibitionShowMain2">
  <div class="exhibitionShowMain2-description">
    <p class="exhibitionShowMain2-description_title">この展覧会について</p>
    <p class="exhibitionShowMain2-description_body"><%= simple_format(@exhibition.description) %></p>
  </div>
  <div class="exhibitionShowMain2-summary">
    <p class="exhibitionShowMain2-summary_title">開催概要</p>
    <p class="exhibitionShowMain2-summary_body"><%= simple_format(@exhibition.summary) %></p>
  </div>
</div>