config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
                       registrations: 'users/registrations',
                       sessions: 'users/sessions'
                     }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'homes/about'

  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'users/leave'
      patch 'users/active_leave'
    end
  end
  resources :exhibitions, only: [:index, :show] do
    resource :congestions, only: [:create]
    resource :clips, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :congestions, dependent: :destroy
  has_many :clips, dependent: :destroy
  has_many :exhibitions, through: :clips

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true, uniqueness: true

  def active_for_authentication?
    super && self.status == "Active"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    exhibitions_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    if super
    else render action: :new
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def after_sign_in_path_for(resource)
    exhibitions_path # ログイン後に遷移するpathを設定
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @exhibitions = current_user.exhibitions.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    begin
    	if @user.update(user_params)
        flash[:success] = "登録情報が変更されました。"
    	  redirect_to user_path(current_user)
    	else
        flash[:danger] = "登録情報の変更に失敗しました。"
    	  render "edit"
    	end
    rescue => e
      flash[:danger] = "エラー"
      redirect_to root_path
    end
  end

  def active_leave
    if current_user.update(status: "Deleted")
      reset_session
      flash[:success] = "ありがとうございました。またのご利用を心よりお待ちしております。"
      redirect_to root_path
    else
      flash[:danger] = "退会に失敗しました。"
      redirect_to user_path(current_user)
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- editエラーメッセージ -->
<% if @user.errors.any? %>
  <%= pluralize(@user.errors.count,"error") %>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>
<!-- editヘディング -->
<h2 class="userEditHeading">登録情報変更</h2>
<!-- editメイン -->
<h4 class="userEditMain-heading">登録情報</h4>
<%= form_for(current_user) do |f| %>
  <div class="row userEditMain-info">
    <div class="col-lg-2 col-md-3 col-5 userEditMain-info_article-name">名前</div>
    <div class="col-lg-3 col-md-4 col-7 userEditMain-info_content-name">
      <%= f.text_field :name, class: "form-control userEditMain-info_content-nameForm" %>
    </div>
  </div>
  <div class="row userEditMain-info">
    <div class="col-lg-2 col-md-3 col-5 userEditMain-info_article-email">メールアドレス</div>
    <div class="col-lg-3 col-md-4 col-7 userEditMain-info_content-email">
      <%= f.text_field :email, class: "form-control userEditMain-info_content-emailForm" %>
    </div>
  </div>
  <div class="row userEditMain-info">
    <%= f.submit '保存', class: "col-lg-1 col-md-2 col-3 btn btn-primary userEditMain-info-submit" %>
  </div>
<% end %>

app/views/users/leave.html.erb
<div class="">
  <!-- 確認文 -->
  <h2 class="userLeave-heading">本当に退会しますか？</h2>
  <!-- 選択ボタン -->
  <div class="row userLeave-choice">
    <div class="col-lg-2 offset-lg-3 userLeave-choice_continue">
      <%= link_to "続ける", user_path(current_user), class: "btn btn-primary userLeave-choice_continueLink" %>
    </div>
    <div class="col-lg-2 offset-lg-3 userLeave-choice_withdrawa">
      <%= link_to "退会する", users_active_leave_users_path, class: "btn btn-danger userLeave-choice_withdrawalLink", method: :patch %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- showヘディング -->
<h2 class="userShowHeading">マイページ</h2>
<!-- showメイン1 -->
<h4 class="userShowMain1-heading">登録情報</h4>
<div class="userShowMain1-info">
  <div class="row userShowMain1-info">
    <div class="col-lg-2 col-md-3 col-5 userShowMain1-info_article-name">名前</div>
    <div class="col-lg-3 col-md-4 col-7 userShowMain1-info_content-name"><%= current_user.name %></div>
  </div>
  <div class="row userShowMain1-info">
    <div class="col-lg-2 col-md-3 col-5 userShowMain1-info_article-email">メールアドレス</div>
    <div class="col-lg-3 col-md-4 col-7 userShowMain1-info_content-email"><%= current_user.email %></div>
  </div>
  <div class="row userShowMain1-info">
    <div class="col-lg-1 col-md-2 col-3 btn btn-primary userShowMain1-info_edit"><%= link_to "変更", edit_user_path(current_user) , class: "userShowMain1-info_editLink"%></div>
    <div class="col-lg-1 col-md-2 col-3 userShowMain1-info_leave"><%= link_to "退会する", users_leave_users_path(current_user) , class: "userShowMain1-info_leaveLink" %></div>
  </div>
</div>
<!-- showメイン2 -->
<h4 class="userShowMain2-heading">クリップした展覧会</h4>
<div class="row userShowMain2-clip">
  <table class="table col-lg-12 userShowMain2-clip_table">
  	<thead class="thead-dark userShowMain2-clip_tableThead">
  	  <tr>
  		<th>会場</th>
  		<th>展覧会名</th>
  		<th>開催期間</th>
      <th></th>
  	  </tr>
  	</thead>
  	<tbody>
  	  <% @exhibitions.each do |exhibition| %>
        <tr>
  	      <td><%= exhibition.place %></td>
  	      <td><%= link_to exhibition.name, exhibition_path(exhibition), class: "userShowMain2-clip_exhibitionLink" %></td>
  	      <td><%= exhibition.start.strftime("%Y年%m月%d日")%> 〜 <%= exhibition.end.strftime("%Y年%m月%d日") %></td>
          <td><%= link_to "削除", exhibition_clips_path(exhibition), class: "userShowMain2-clip_clippedLink", method: :delete %></td>
        </tr>
  	 <% end %>
  	</tbody>
  </table>
  <!-- ページネーション -->
  <%= paginate @exhibitions, class: "userShowMain2-clip_paginate" %>
</div>