config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
                       registrations: 'users/registrations',
                       sessions: 'users/sessions'
                     }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'homes/about'

  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'users/leave'
      patch 'users/active_leave'
    end
  end
  resources :exhibitions, only: [:index, :show] do
    resource :congestions, only: [:create]
    resource :clips, only: [:create, :destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clip.rb
class Clip < ApplicationRecord
  belongs_to :user
  belongs_to :exhibition
end

app/models/congestion.rb
class Congestion < ApplicationRecord
  belongs_to :user
  belongs_to :exhibition

  def self.delete_test
    Congestion.delete_all
  end
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  has_many :clips, dependent: :destroy
  has_many :congestions, dependent: :destroy
  has_many :users, through: :clips

  mount_uploader :image, ImageUploader

  validates :name, presence: true, length: { maximum: 50 }
  validates :place, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :image, presence: true
  validates :description, presence: true, length: { maximum: 2000 }
  validates :summary, presence: true, length: { maximum: 2000 }
  validates :status, presence: true

  def congested_by?(user)
    congestions.where(user_id: user.id).exists?
  end

  def clipped_by?(user)
    clips.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :congestions, dependent: :destroy
  has_many :clips, dependent: :destroy
  has_many :exhibitions, through: :clips

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true, uniqueness: true

  def active_for_authentication?
    super && self.status == "Active"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # アプリケーション全体でエラーを拾う
  # StandardError=通常のプログラムで発生する可能性の高い例外クラス ex)ArgumentError NameError NoMethodError etc.
    rescue_from ActiveRecord::RecordNotFound, with: :render_404
    rescue_from StandardError, with: :render_500

    # 存在しないページへのアクセス時 eはエラー内容を格納する引数？
    def render_404
      render template: 'errors/error404', status: 404, layout: 'application', content_type: 'text/html'
    end
    # サーバーの内部にエラーが発生
    def render_500
      render template: 'errors/error500', status: 500, layout: 'application', content_type: 'text/html'
    end

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  def create
  	exhibition = Exhibition.find(params[:exhibition_id])
  	clip = current_user.clips.new(exhibition_id: exhibition.id)
    if clip.save
  	  flash[:success] = "クリップしました。"
  	  redirect_back(fallback_location: root_path)
  	else
  	  flash[:danger] = "クリップに失敗しました。"
  	  redirect_to root_path
    end
  end

  def destroy
  	exhibition = Exhibition.find(params[:exhibition_id])
  	clip = current_user.clips.find_by(exhibition_id: exhibition.id)
  	if clip.destroy
  	  flash[:success] = "クリップを外しました。"
  	  redirect_back(fallback_location: root_path)
  	else
  	  flash[:danger] = "クリップを外すのに失敗しました。"
  	  redirect_to root_path
    end
end

  private
  def clip_params
  	params.require(:clip).permit(:user_id, :exhibition_id)
  end
end

app/controllers/congestions_controller.rb
class CongestionsController < ApplicationController
  def create
    exhibition = Exhibition.find(params[:exhibition_id])
  	congestion = current_user.congestions.new(congestion_params)
    if congestion.save
  	  redirect_back(fallback_location: root_path)
    else
      redirect_to root_path
      flash[:danger] = "混雑度の投稿に失敗しました。"
    end
  end

  private
  def congestion_params
  	params.permit(:user_id, :exhibition_id, :condition)
  end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :authenticate_user!
  before_action :congestion_delete, only: [:index, :show]

  def index
  	@exhibitions = Exhibition.all
  end

  def show
  	@exhibition = Exhibition.find(params[:id])
  end

  private
  def congestion_delete
    Congestion.where("created_at<?",Time.current.ago(1.hours)).delete_all
  end

  def exhibition_params
    params.require(:exhibition).permit(:name, :place, :start, :end, :image, :description, :summary, :status)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    if super
    else render action: :new
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def after_sign_in_path_for(resource)
    exhibitions_path # ログイン後に遷移するpathを設定
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @exhibitions = current_user.exhibitions.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    begin
    	if @user.update(user_params)
        flash[:success] = "登録情報が変更されました。"
    	  redirect_to user_path(current_user)
    	else
        flash[:danger] = "登録情報の変更に失敗しました。"
    	  render "edit"
    	end
    rescue => e
      flash[:danger] = "エラー"
      redirect_to root_path
    end
  end

  def active_leave
    if current_user.update(status: "Deleted")
      reset_session
      flash[:success] = "ありがとうございました。またのご利用を心よりお待ちしております。"
      redirect_to root_path
    else
      flash[:danger] = "退会に失敗しました。"
      redirect_to user_path(current_user)
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/congestions_helper.rb
module CongestionsHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>わかるくん - 混雑度実況投稿アプリ〜これで上野の美術館・博物館の混雑度がわかる〜</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet">
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <!-- appヘッダー -->
    <header class="container-fluid appHeader">
      <nav class="row appHeader_nav">
        <div class="col-lg-1 col-md appHeader_nav-logo"><%= link_to 'Wakarukun', root_path, class: "appHeader_link" %></div>
          <!-- ログイン条件分岐 -->
          <% if user_signed_in? %>
            <div class="col-lg-1 offset-lg-7 col-md appHeader_nav-about"><%= link_to 'About', homes_about_path, class: "appHeader_link" %></div>
            <div class="col-lg-1 col-md appHeader_nav-exhibition"><%= link_to 'Exhibition', exhibitions_path, class: "appHeader_link" %></div>
            <div class="col-lg-1 col-md appHeader_nav-mypage"><%= link_to 'Mypage', user_path(current_user), class: "appHeader_link" %></div>
            <div class="col-lg-1 col-md appHeader_nav-logout"><%= link_to 'Logout', destroy_user_session_path, class: "appHeader_link-blue", method: :delete %></div>
          <% else %>
            <div class="col-lg-1 offset-lg-8 col-md appHeader_nav-about"><%= link_to 'About', homes_about_path, class: "appHeader_link" %></div>
            <div class="col-lg-1 col-md appHeader_nav-login"><%= link_to 'Log in', new_user_session_path, class: "appHeader_link" %></div>
            <div class="col-lg-1 col-md appHeader_nav-signup"><%= link_to 'Sign up',new_user_registration_path, class: "appHeader_link-blue" %></div>
          <% end %>
      </nav>
    </header>
    <!-- appメイン -->
      <div class="container appMain_container">
        <section class="appSection">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <p class="success"><%= flash[:success] %></p>
          <p class="danger"><%= flash[:danger] %></p>
        </section>
      <%= yield %>
      </div>
    <!-- appフッター -->
    <footer class="container-fluid appFooter">
      <div class="row appFooter">
        <span class="col-lg-12 appFooter_copyright">&copy;2020 student</span>
      </div>
    </footer>
  </body>
</html>